spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.kafka.bootstrap-servers=localhost:9092

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.root=INFO

payment.provider=${PAYMENT_PROVIDER:mock}
payment.retry.max-attempts=${PAYMENT_RETRY_MAX_ATTEMPTS:3}
payment.retry.max-attempts-recovery-job=${PAYMENT_RETRY_MAX_ATTEMPTS_RECOVERY_JOB:10}
payment.retry.initial-delay-ms=${PAYMENT_RETRY_INITIAL_DELAY_MS:1000}
payment.retry.multiplier=${PAYMENT_RETRY_MULTIPLIER:2.0}
payment.retry.max-backoff-ms=${PAYMENT_RETRY_MAX_BACKOFF_MS:10000}

